# for debug only use
version: "2.2"

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    image: ubuntu:20.04
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./:/src
    working_dir: /src
    command: ./target/debug/event-manager-telegram-bot
    ports:
      - "3000:3000"
