- hosts: app
  become: true
  gather_facts: yes
  tasks:
    - name: Download release
      get_url:
        url: https://github.com/openworld-community/event-manager-telegram-bot-frontend/releases/download/{{ version }}/event-manager-telegram-bot-front.tar.gz
        dest: /tmp/event-manager-telegram-bot-front-{{version}}.tar.gz
        ssl_no_verify: yes

    - name: Unpack release
      unarchive:
          src: /tmp/event-manager-telegram-bot-front-{{version}}.tar.gz
          dest: /var/www/event-manager-telegram-bot-front-{{version}}
          remote_src: yes
          creates: /var/www/event-manager-telegram-bot-front-{{version}}

    - name: Remove old symlink
      file:
        path: /var/www/{{ ansible_fqdn }}
        state: absent
        force: yes

    - name: Create new symlink
      file:
          src: /var/www/event-manager-telegram-bot-front-{{version}}
          dest: /var/www/{{ ansible_fqdn }}
          state: link
          force: yes

    - name: Nginx reload
      service:
        name: nginx
        state: reloaded