- hosts: app
  become: true
  gather_facts: yes
  tasks:
    - name: Unpack release
      unarchive:
        src: https://github.com/openworld-community/event-manager-bot-frontend/releases/download/{{ version }}/event-manager-telegram-bot-front.tar.gz
        dest: /var/www/event-manager-telegram-bot-front-{{version}}
        remote_src: yes
        creates: /var/www/event-manager-telegram-bot-front-{{version}}
        mode: '0755'

    - name: Remove old symlink
      file:
        path: /var/www/{{ inventory_hostname }}
        state: absent
        force: yes

    - name: Create new symlink
      file:
          src: /var/www/event-manager-telegram-bot-front-{{version}}
          dest: /var/www/{{ inventory_hostname }}
          state: link
          force: yes

    - name: Nginx reload
      service:
        name: nginx
        state: reloaded