name: Delete old releases

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: Delete old releases
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -X GET https://api.github.com/repos/${{ github.repository }}/releases \
          | jq -r '.[] | .id' \
          | tail -n +6 \
          | xargs -I {} curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -X DELETE https://api.github.com/repos/${{ github.repository }}/releases/{}
