on:
  repository_dispatch:
    types:
      - frontend_deploy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: ${{ github.event.client_payload.env }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: hmarr/debug-action@v2

      - name: Debug
        run: |
          echo "GITHUB_REF: ${{ github.event.client_payload.env }}"
          echo "GITHUB_REF: ${{ github.event.client_payload.version }}"

      - name: Deploy frontend
        run: |
          ansible-galaxy install -r iaac/ansible/roles/requirements.yml
          eval "$(ssh-agent -s)"
          echo -n ${{ secrets.DEPLOY_SSH_KEY }} | base64 -d | ssh-add -
          ansible-playbook --user ${{ secrets.DEPLOY_SSH_USER }} -i iaac/ansible/inventory \
          --limit ${{ github.event.client_payload.env }} \
          iaac/ansible/playbooks/frontend.yml --extra-vars "\
          ansible_sudo_pass=\"${{ secrets.DEPLOY_USER_PASSWORD }}\""