//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "reservation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub event: i32,
    pub user: i32,
    pub user_name1: String,
    pub user_name2: String,
    pub adults: i32,
    pub children: i32,
    pub waiting_list: i32,
    pub ts: DateTime,
    pub payment: String,
    pub state: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event::Entity",
        from = "Column::Event",
        to = "super::event::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Event,
}

impl Related<super::event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Event.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
